Feature/code review
Kgomotso196/Code-Review pull request #1
Opened 2023-02-20 20:55 UTC by Kgomotso196

**My Page**

> Structured and styled a website using HTML and CSS.

> Showed my understanding of using list tags.

2023-02-20 21:40 UTC, Kgomotso196 commented
Hi there @Kgomotso196 , good job so far!🎉 But you are almost there, you just need little changes.
![image](https://user-images.githubusercontent.com/74494438/220202196-1ffb927e-2ef1-4d57-a1d0-64a46e10ffe0.png)

STATUS:REQUIRED CHANGES
Check the comments.

2023-02-20 21:58 UTC, Kgomotso196 commented
```
 <div id="tribute-info">
    <h3 id="headline">Here's a time line of Dr. Boulaug's life:</h3>
    <ul>
      <li>
        <strong>1914</strong> - Born in Cresco, lowa
      </li>
      <li>
        <strong>1933</strong>- Leaves his family's farm to attend the University of Minnesota, thanks to a Depression era program known as the "National Youth Administration"
      </li>
      <li>
        <strong>1935</strong> - Has to stop school and save up more money. Works in the Civilian Conservation Corps, helping starving Americans. "I saw how food changed them", he said. "All of this left scars on me." </li>
      <li>
        <strong>1938</strong> - Marries wife of 69 years Margret Gibson. Gets laid off due to budget cuts. Inspired by Elvin Charles Stakman, he returns to school study under Stakman, who teaches him about breeding pest-resistent plants.      <li>
        <strong>1941</strong>- Tries to enroll in the military after the Pearl Harbor attack, but is rejected. Instead, the military asked his lab to work on waterproof glue, DDT to control malaria, disinfectants, and other applied science.  </li>      <li>
        <strong>1942</strong> - Receives a Ph.D. in Genetics and Plant Pathology    </li>      <li>
        <strong>1944</strong> - Rejects a 100% salary increase from Dupont, leaves behind his pregnant wife, and flies to Mexico to head a new plant pathology program. Over the next 16 years, his team breeds 6,000 different strains of disease resistent wheat - including different varieties for each major climate on Earth. </li>      <li>
        <strong>1945</strong>- Discovers a way to grown wheat twice each season, doubling wheat yields   </li>      <li>
        <strong>1953</strong> - crosses a short, sturdy dwarf breed of wheat with a high-yeidling American breed, creating a strain that responds well to fertilizer. It goes on to provide 95% of Mexico's wheat.     </li>      <li>
        <strong>1962</strong> - Visits Delhi and brings his high-yielding strains of wheat to the Indian subcontinent in time to help mitigate mass starvation due to a rapidly expanding population  </li>
        <li>
            <strong>1970</strong> - receives the Nobel Peace Prize</li> 
            <li>
            <strong>1983</strong>- helps seven African countries dramatically increase their maize and sorghum yields   </li>      <li>
            <strong>1984</strong>- becomes a distinguished professor at Texas A&M University   </li>      <li>
            <strong>2005</strong> - states "we will have to double the world food supply by 2050." Argues that genetically modified crops are the only way we can meet the demand, as we run out of arable land. Says that GM crops are not inherently dangerous because "we've been genetically modifying plants and animals for a long time. Long before we called it science, people were selecting the best breeds." </li>
        
            <li>
              <strong>2009</strong> - dies at the age of 95.</li> 
          </ul>
          <blockquote>
            <p>"Borlaug's life and achievement are testimony to the far-reaching contribution that one man's towering intellect, persistence and scientific vision can make to human peace and progress."</p>
          <cite>-- Indian Prime Minister Manmohan Singh</cite>
          </blockquote>
        <p>If you have time, you should read more about this incredible human being on his<a id="tribute-link" target="_blank" href="https://en.wikipedia.org/wiki/Norman_Borlaug">Wikipedia entry</a></p>
      </div>

```

- Can you change your main tags to use section tags instead? This also helps when you want to run your code on the online server.
- Don't forget to give space in between your styles. Also check out how linters are used.
```

```

2023-02-20 22:02 UTC, Kgomotso196 commented
```
  <head>
    <meta charset="UTF-8">
    <title>Fork Me! FCC: Test Suite Template</title>
    <link rel="stylesheet" href="css/style.css">
  </head>
```

- Your style.css is not in the directory(css folder) you claim it to be in, please carefully check where your style.css is in.

2023-02-20 22:14 UTC, iambenkis commented
> ```
>   <head>
>     <meta charset="UTF-8">
>     <title>Fork Me! FCC: Test Suite Template</title>
>     <link rel="stylesheet" href="css/style.css">
>   </head>
> ```
> 
> * Your style.css is not in the directory(css folder) you claim it to be in, please carefully check where your style.css is in.

Kindly explain the why of your comments to make sure the person you are reviewing understand why they're going to make this changes :+1:

2023-02-20 22:14 UTC, iambenkis commented
> ```
>  <div id="tribute-info">
>     <h3 id="headline">Here's a time line of Dr. Boulaug's life:</h3>
>     <ul>
>       <li>
>         <strong>1914</strong> - Born in Cresco, lowa
>       </li>
>       <li>
>         <strong>1933</strong>- Leaves his family's farm to attend the University of Minnesota, thanks to a Depression era program known as the "National Youth Administration"
>       </li>
>       <li>
>         <strong>1935</strong> - Has to stop school and save up more money. Works in the Civilian Conservation Corps, helping starving Americans. "I saw how food changed them", he said. "All of this left scars on me." </li>
>       <li>
>         <strong>1938</strong> - Marries wife of 69 years Margret Gibson. Gets laid off due to budget cuts. Inspired by Elvin Charles Stakman, he returns to school study under Stakman, who teaches him about breeding pest-resistent plants.      <li>
>         <strong>1941</strong>- Tries to enroll in the military after the Pearl Harbor attack, but is rejected. Instead, the military asked his lab to work on waterproof glue, DDT to control malaria, disinfectants, and other applied science.  </li>      <li>
>         <strong>1942</strong> - Receives a Ph.D. in Genetics and Plant Pathology    </li>      <li>
>         <strong>1944</strong> - Rejects a 100% salary increase from Dupont, leaves behind his pregnant wife, and flies to Mexico to head a new plant pathology program. Over the next 16 years, his team breeds 6,000 different strains of disease resistent wheat - including different varieties for each major climate on Earth. </li>      <li>
>         <strong>1945</strong>- Discovers a way to grown wheat twice each season, doubling wheat yields   </li>      <li>
>         <strong>1953</strong> - crosses a short, sturdy dwarf breed of wheat with a high-yeidling American breed, creating a strain that responds well to fertilizer. It goes on to provide 95% of Mexico's wheat.     </li>      <li>
>         <strong>1962</strong> - Visits Delhi and brings his high-yielding strains of wheat to the Indian subcontinent in time to help mitigate mass starvation due to a rapidly expanding population  </li>
>         <li>
>             <strong>1970</strong> - receives the Nobel Peace Prize</li> 
>             <li>
>             <strong>1983</strong>- helps seven African countries dramatically increase their maize and sorghum yields   </li>      <li>
>             <strong>1984</strong>- becomes a distinguished professor at Texas A&M University   </li>      <li>
>             <strong>2005</strong> - states "we will have to double the world food supply by 2050." Argues that genetically modified crops are the only way we can meet the demand, as we run out of arable land. Says that GM crops are not inherently dangerous because "we've been genetically modifying plants and animals for a long time. Long before we called it science, people were selecting the best breeds." </li>
>         
>             <li>
>               <strong>2009</strong> - dies at the age of 95.</li> 
>           </ul>
>           <blockquote>
>             <p>"Borlaug's life and achievement are testimony to the far-reaching contribution that one man's towering intellect, persistence and scientific vision can make to human peace and progress."</p>
>           <cite>-- Indian Prime Minister Manmohan Singh</cite>
>           </blockquote>
>         <p>If you have time, you should read more about this incredible human being on his<a id="tribute-link" target="_blank" href="https://en.wikipedia.org/wiki/Norman_Borlaug">Wikipedia entry</a></p>
>       </div>
> ```
> 
> * Can you change your main tags to use section tags instead? This also helps when you want to run your code on the online server.
> * Don't forget to give space in between your styles. Also check out how linters are used.
> 
> ```
> 
> ```

Kindly explain the why of your comments to make sure the person you are reviewing understand why they're going to make this changes :+1:

2023-02-20 22:15 UTC, iambenkis requested changes
# Required Changes :recycle:
![almost-there](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp9z2Rq_bAJ42eRNxObBr1nKDUbZjLw2QqkQ&usqp=CAU)

### Hey @Kgomotso196  :wave:

### Highlights :1st_place_medal:

:heavy_check_mark: The student phrased the comments politely
:heavy_check_mark: The student comments are clear and easy to understand 
:heavy_check_mark: 2 comments in the review.


Good job on implementing most of the requirements but there are some issues that you still need to work on to go to the next project, but you are almost there! :blush:


# Require Changes

- [ ] Good job adding comments to the review , however you should add at least two inline comments :+1: , kindly add them to meet the requirements :+1: . For more about inline comment check [this link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request)

- [ ] Kindly explain the why of your comments to make sure the person you are reviewing understand why they're going to make this changes :+1: 


- [ ] Kindly use some emoji and GIF :smile: to make your comments more friendly :hugs: 

# Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @iambenkis in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 13:03 UTC, Kgomotso196 commented on index.html
> +    <script  src="js/index.js"></script>
> **Dear @Kgomotso196 Kindly check the directory that you used for your style.css, you included the directory named "css" but in actual fact there's no folder named "css" in your project.Also check the "js" directory you included in your index.html. You could create folders "css" and "js" and move your css and js files respectively in those folders. Other than that, I would suggest you remove those folders since you have not added them on your project. This is to help your html code link to the css file that has all the styles that need to be applied to your index.html. If you don't embed your css correctly its content won't be applied to your html file. But you are almost there😊🥳**

2023-02-21 13:25 UTC, Kgomotso196 commented on index.html
> +            <strong>1983</strong>- helps seven African countries dramatically increase their maize and sorghum yields   </li>      <li>
Hey @Kgomotso196 ,😊 you are so close.
**Changes Required♻ :**
Other than that, you have done.

![212969210-69f495ba-f2fb-4559-a222-d1507310d6fb](https://user-images.githubusercontent.com/74494438/220355621-9bd39dc0-b76b-4cf9-a3bc-5bc62d40744f.gif)
 
Remember to use section tags instead of main tags.😊 This is to help you group related content. Section tags can  contain any content that is repeated across documents such as sidebars, navigation links, copyright information, site logos, and search forms. This is also supported by web browsers.

**HAPPY CODING.🥳**

2023-02-21 15:21 UTC, merged